### ISSUE TITLE
compan-sourcekit slow or I am missing something?

### ISSUE THREAD

**Issue by LucaMarconato** [nathankot/company-sourcekit#21] opened 2016-10-29 22:09 UTC
Hello, I have set up company-sorcekit and now if I type "CGRect(" after a fraction of second it appears a list of suggestion, as in your demo video.

**soft question:** is it possible to make that fraction of second smaller? For instance with company I use
(setq company-idle-delay 0.01)
(setq company-dabbrev-downcase 0.01)
in order to cut the time that I have to wait before seeing the suggestions, but this does not seem to affect company-sourcekit.

But the **real problem** is the following: If I type (inside a method of a class) "self.", the suggestions are showed after 5 seconds! It is an eternity!
This happen also with various other variables.

Is this the default behaviour, is it a known bug or maybe I am not using company-sourcekit correctly?
I would like to cut down that time or to bind a key, for instance S-TAB, to the function that shows the suggestions. In other word I would like that typing "self." (or maybe typing "self." S-TAB) emacs would show me the suggestions immediately.
Is it possible?

Thank you in advance!
Luca.

**Comment by nathankot** [comment] 2016-10-31 02:52
Hey Luca - thanks for voicing your concerns! The speed of completion is highly dependent on your Xcode version, and the project you're working on. The best we can achieve is probably to match the speed of completion of Xcode - currently it doesn't and there are improvements that can be made to do that. Most of these improvements would be applied on the sourcekittendaemon side of things.

Please take a look at the relevant issues below:

https://github.com/terhechte/SourceKittenDaemon/issues/40
https://github.com/nathankot/company-sourcekit/issues/16

Pretty much it boils down to us not doing the same amount of caching of sourcekit responses that Xcode is doing.

**Comment by nathankot** [comment] 2017-01-16 00:11
Closing as duplicate of #24

**Closed as completed by nathankot** 2017-01-16 00:11 UTC
